# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('text', models.CharField(max_length=5000)),
                ('audio', models.FileField(null=True, upload_to='uploads/audio/%Y/%m/')),
                ('english_audio', models.FileField(null=True, upload_to='uploads/audio/%Y/%m/')),
                ('image', models.ImageField(null=True, upload_to='uploads/image/%Y/%m/')),
            ],
        ),
    ]
